export const surpriseMePrompts = [
  'uma poltrona em forma de abacate',
  'uma pintura a óleo surrealista onírica de Salvador Dalí de um gato jogando damas',
  'ursinhos de pelúcia comprando mantimentos no Japão, ukiyo-e',
  'uma pintura a óleo de Matisse de um robô humanóide jogando xadrez',
  'panda cientista louco misturando produtos químicos brilhantes, arte digital',
  'uma fotografia macro 35mm de dois ratos no Havaí, cada um deles vestindo minúsculos maiôs e carregando pequenas pranchas de surfe, arte digital',
  'renderização 3D de um peixe tropical bonito em um aquário em um fundo azul escuro, arte digital',
  'um astronauta descansando em um resort tropical no espaço, vaporwave',
  'um retrato de pintura a óleo de uma capivara vestindo vestes reais medievais e uma coroa ornamentada em um fundo escuro',
  'um vitral representando um hambúrguer e batatas fritas',
  'um desenho a lápis e aquarela de uma cidade brilhante no futuro com carros voadores',
  'um lounge interno iluminado pelo sol com uma piscina de água transparente e outra piscina com água rosa pastel translúcida, ao lado de uma grande janela, arte digital',
  'um shiba inu adivinhador lendo seu destino em um hambúrguer gigante, arte digital',
  '"uma lontra marinha com um brinco de pérola" de Johannes Vermeer',
  'um desenho a pastel de óleo de um gato irritado em uma nave espacial',
  'uma pintura de uma raposa no estilo da Noite Estrelada',
  'uma tigela de sopa que parece um monstro, tricotada de lã',
  'Um robô de pelúcia sentado contra uma parede amarela',
  'Um pôr do sol estilo synthwave acima da água refletida do mar, arte digital',
  'Duas torres futuristas com uma passarela coberta por folhagem exuberante, arte digital',
  'Uma renderização 3D de um balão de ar quente colorido arco-íris voando sobre um lago reflexivo',
  'Uma capa de quadrinhos de um super-herói usando fones de ouvido',
  'Uma explosão centrada de pó colorido em um fundo preto',
  'Uma foto de um cachorro Samoieda com a língua de fora abraçando um gato siamês branco',
  'Uma foto de um monstro de pelo branco parado em uma sala roxa',
  'Uma foto da escultura de Michelangelo de David usando fones de ouvido como DJ',
  'Um Samurai andando a cavalo em Marte, lomografia.',
  'Um Cadillac moderno e elegante percorre a via expressa Gardiner com o centro de Toronto ao fundo, com um reflexo de lente, fotografia de 50 mm',
  'Uma fotografia realista de uma jovem de olhos azuis e cabelos loiros',
  'Um homem parado na frente de um stargate para outra dimensão',
  'Bob Esponja Calça Quadrada no Projeto Bruxa de Blair',
  'Um velociraptor trabalhando em uma barraca de cachorro-quente, lomografia',
  'Um homem andando pelas ruas movimentadas de Kowloon à noite, iluminado por muitos letreiros luminosos de lojas em neon, lente de 50 mm',
  'Um churrasco com vida, no estilo animação da Pixar',
  'Um clube de dança ciborgue futurista, luzes de néon',
  'O Anime Japonês Star Wars 1990 há muito perdido',
  'Um hambúrguer em forma de cubo de Rubik, fotografia de comida profissional',
  'Um porco-espinho Synthwave, Blade Runner Cyberpunk',
  'Um astronauta encontrando uma forma de vida alienígena em um planeta distante, fotografia',
  'Um dinossauro explorando a Cidade do Cabo, fotografia',
  'Um homem se apaixonando por seu computador, arte digital',
  'Uma fotografia de um ciborgue explorando Tóquio à noite, lomografia',
  'Drácula andando pelas ruas da cidade de Nova York na década de 1920, fotografia em preto e branco',
  'avião Synthwave',
  'Um homem vagueia pelas ruas chuvosas de Tóquio, com luminosos letreiros de néon, 50mm',
  'Um ônibus espacial voando sobre a Cidade do Cabo, arte digital',
]
